# Generated by Django 4.2.30 on 2026-09-20 15:41

from django.db import migrations, models
import django.db.models.deletion



def transfer_bookings(apps, schema_editor):
    from datetime import datetime, timedelta
    from zoneinfo import ZoneInfo
    import re

    Pupil = apps.get_model('website', 'Pupil')
    Booking = apps.get_model('website', 'Booking')
    Order = apps.get_model('website', 'Order')
    Slot = apps.get_model('website', 'AvailabilitySlot')
    alias = schema_editor.connection.alias
    seen = set()
    for pupil in Pupil.objects.using(alias).all():
        number = re.sub(r'[\s().-]', '', pupil.phone_number)
        if number.startswith('00'):
            number = '+' + number[2:]
        if number.startswith('0'):
            number = '+44' + number[1:]
        elif number.startswith('44'):
            number = '+' + number
        if not re.fullmatch(r'\+[1-9][0-9]{7,14}', number) or number in seen:
            raise RuntimeError('Resolve invalid or duplicate pupil phone numbers before migrating.')
        seen.add(number)
        pupil.phone_number = number
        pupil.save(using=alias)
    packages = {'single': (1, '59.00'), 'block': (10, '570.00'), 'intro': (3, '175.00')}
    for booking in Booking.objects.using(alias).all():
        if booking.lesson_type == 'intro' and Order.objects.using(alias).filter(pupil_id=booking.pupil_id, package='intro').exists():
            raise RuntimeError('Resolve repeated legacy intro bookings before migrating.')
        starts_at = datetime.combine(booking.date, booking.time, tzinfo=ZoneInfo('Europe/London'))
        if Slot.objects.using(alias).filter(starts_at__gt=starts_at-timedelta(minutes=90), starts_at__lt=starts_at+timedelta(minutes=90)).exists():
            raise RuntimeError('Resolve overlapping legacy bookings before migrating.')
        count, price = packages[booking.lesson_type]
        order = Order.objects.using(alias).create(pupil_id=booking.pupil_id, package=booking.lesson_type, lesson_count=count, total_price=price)
        Order.objects.using(alias).filter(pk=order.pk).update(created_at=booking.created_at)
        slot = Slot.objects.using(alias).create(starts_at=starts_at)
        booking.order_id = order.pk
        booking.slot_id = slot.pk
        booking.save(using=alias)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('single', '90-minute lesson'), ('block', '10 lesson block'), ('intro', 'New pupil introductory offer')], max_length=20)),
                ('lesson_count', models.PositiveSmallIntegerField(editable=False)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='website.pupil'),
        ),
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='website.order'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='website.availabilityslot'),
        ),
        migrations.RunPython(transfer_bookings),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pupil',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AlterField(
            model_name='booking', name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='website.order'),
        ),
        migrations.AlterField(
            model_name='booking', name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='website.availabilityslot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('order', 'lesson_number'), name='unique_lesson_in_order'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('lesson_number__gte', 1)), name='positive_lesson_number'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('package', 'intro')), fields=('pupil',), name='one_intro_order_per_pupil'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('lesson_count__gte', 1)), name='order_has_lessons'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='order_price_nonnegative'),
        ),
    ]
